gems:
- jekyll-sitemap   # Create a sitemap using the official Jekyll sitemap gem
- jekyll-feed   # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
permalink: /:title/
name: Long Tran
sass:
  style: :expanded # You might prefer to minify using :compressed

url:
baseurl: /blogs
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'
version: v1.2.0
avatar: https://avatars1.githubusercontent.com/u/21163398?s=400&u=dcf98eb1ef275ae3f24fcc0419e6a1bdb5565786&v=4
google_analytics:
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
disqus:
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: barryclark/jekyll-now
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: jekyllrb
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


description: Personal blog
